//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by YegrinStudio.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_YEGRINSTUDIO_DIALOG         102
#define IDR_MAINFRAME                   128
#define IDB_BKGND_BMP                   129
#define IDR_MAIN_MENU                   131
#define IDB_UPPERTAB_IMAGE              132
#define IDD_UPPER_DIALOG                133
#define IDD_LOWER_FLASH_DIALOG          134
#define IDD_LOWER_AUXILIARY_DIALOG      135
#define IDD_LOWER_INFORMATION_DIALOG    136
#define IDD_LOWER_MEMORY_DIALOG         137
#define IDD_LOWER_GROUP_SYNC_DIALOG     138
#define IDI_TEST_ICON                   139
#define IDI_ICONA                       140
#define IDI_ICONB1                      141
#define IDI_ICONB2                      142
#define IDI_DEVICE_ICON                 143
#define IDI_PLUS_ICON                   144
#define IDI_MINUS_ICON                  145
#define IDI_ICON_MODLOFF                146
#define IDI_ICON_MODLON                 147
#define IDC_HAND                        148
#define IDI_ICON_LEDON                  149
#define IDI_ICON_LEDOFF                 150
#define IDI_ICON_SOUNDOFF               151
#define IDI_ICON_SOUNDON                152
#define IDI_ICON_MODEON                 153
#define IDI_ICON_MODEOFF                154
#define IDI_ICON_HOLDON                 155
#define IDI_ICON_HOLDOFF                156
#define IDI_ICON_PCELLON                157
#define IDI_ICON_PCELLOFF               158
#define IDI_ICON_RFON                   159
#define IDI_ICON_RFOFF                  160
#define IDI_ICON_CHARGEOFF              161
#define IDI_ICON_CHARGEON               162
#define IDI_ICON_TESTON                 163
#define IDI_ICON_TESTOFF                164
#define IDB_BITMAP_LEDON                165
#define IDB_BITMAP_LEDOFF               166
#define IDD_DEBUG_DIALOG                167
#define IDB_BITMAP_FUNCTIONSON          168
#define IDB_BITMAP_FUNCTIONSOFF         169
#define IDB_MATRIXSMALL                 170
#define IDB_MATRIXTINY                  171
#define IDB_MATRIXLARGE                 172
#define IDB_BITMAP_PLUS                 173
#define IDB_BITMAP_MINUS                174
#define IDD_SETUP_DIALOG                175
#define IDB_BITMAP_A                    176
#define IDB_BITMAP_B1                   178
#define IDB_BITMAP_B2                   179
#define IDI_ICON_SAMPLE1                180
#define IDB_BKGND_YEGRINIMAGE           181
#define IDB_UPPERTAB_IMAGE_SAMPLE       182
#define IDI_ICON1                       191
#define IDB_BITMAP_MODLON               192
#define IDC_TAB1                        1000
#define IDC_UPPER_TAB                   1000
#define IDC_EDT_RVCDATA                 1001
#define IDC_SKIN                        1001
#define IDC_BUTTON1                     1002
#define IDC_SKIN_SETUP                  1003
#define IDC_MODL_BUTTON                 1006
#define IDC_SOUND_BUTTON                1007
#define IDC_MODE_BUTTON                 1008
#define IDC_HOLD_BUTTON                 1009
#define IDC_UPPER_PLUS_BUTTON           1010
#define IDC_LOWER_TAB                   1011
#define IDC_UPPWER_MINUS_BUTTON         1011
#define IDC_LOWER_PLUS_BUTTON           1012
#define IDC_EDIT2                       1013
#define IDC_LOWER_MINUS_BUTTON          1013
#define IDC_EDT_SENDHIS                 1013
#define IDC_EDIT_DELAY                  1013
#define IDC_EDIT3                       1014
#define IDC_PCELL_BUTTON                1014
#define IDC_COB_PORT                    1014
#define IDC_RF_BUTTON                   1015
#define IDC_COB_BAUD                    1015
#define IDC_SPIN1                       1016
#define IDC_CHARGE_BUTTON               1016
#define IDC_COB_DATA                    1016
#define IDC_SPIN_FLASH                  1016
#define IDC_SPIN2                       1017
#define IDC_CHECK1                      1017
#define IDC_TEST_BUTTON                 1017
#define IDC_COB_PTY                     1017
#define IDC_SPIN_DELAY                  1017
#define IDC_COMBO1                      1018
#define IDC_CHECK2                      1018
#define IDC_COB_STOP                    1018
#define IDC_COMBO2                      1019
#define IDC_EDIT1                       1019
#define IDC_CHECK3                      1019
#define IDC_EDT_SENDDATA                1019
#define IDC_BTN_CONNECT                 1020
#define IDC_EDIT4                       1020
#define IDC_BTN_SENDING                 1021
#define IDC_EDIT5                       1021
#define IDC_BUTTON2                     1023
#define IDC_BTN_EXIT                    1024
#define IDC_CMD_COMBO                   1025
#define IDC_READ_RADIO                  1030
#define IDC_WRITE_RADIO                 1031
#define IDC_CHECK_HEXA                  1032
#define IDC_STATIC_MODL1                1040
#define IDC_STATIC_MODL2                1041
#define IDC_STATIC_MODL3                1042
#define IDC_STATIC_MODL4                1043
#define IDC_DEBUG_EDIT                  1044
#define IDC_STATIC_SOUND                1045
#define IDC_STATIC_MODE                 1046
#define IDC_STATIC_HOLD                 1047
#define IDC_STATIC_PCELL                1048
#define IDC_STATIC_RF                   1049
#define IDC_STATIC_CHARGE1              1050
#define IDC_STATIC_CHARGE2              1051
#define IDC_STATIC_TEST                 1052
#define IDC_STATIC_FUNCTIONS            1053
#define IDC_STATIC_DEVAINFO             1054
#define IDC_STATIC_DEVB1INFO            1055
#define IDC_STATIC_DEVB2INFO            1056
#define IDC_SKIN_UP                     1058
#define IDC_SKIN_L1                     1061
#define IDC_SKIN_L2                     1062
#define IDC_SKIN_L3                     1063
#define IDC_SKIN_L4                     1064
#define IDC_SKIN_L5                     1065
#define IDC_SPIN3                       1068
#define IDC_SPIN_DEVAINFO               1068
#define IDC_SPIN4                       1069
#define IDC_EDIT_FLASH                  1069
#define IDC_SPIN_DEVB1INFO              1069
#define IDC_SPIN_DEVB2INFO              1070
#define IDC_SPIN5                       1070
#define IDC_COMBO_BRACKETING            1071
#define IDC_BUTTON_TEST                 1072
#define IDC_EDIT_RCVTEST                1073
#define IDC_BUTTON_B1                   2004
#define IDC_BUTTON_B2                   2005
#define IDC_BUTTON_A                    2020
#define ID_MENUITEM_CONNECT             32774
#define ID_MENUITEM_FILE                32775
#define ID_MENUITEM_EXTENSION           32779
#define ID_MENUITEM_GROUP1              32781
#define ID_MENUITEM_GROUP2              32782
#define ID_MENUITEM_GROUP3              32783
#define ID_MENUITEM_GROUP4              32784
#define ID_MENUITEM_GROUP5              32785
#define ID_MENUITEM_SETTUP              65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        194
#define _APS_NEXT_COMMAND_VALUE         32786
#define _APS_NEXT_CONTROL_VALUE         1074
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
